const List<Map<String, String>> translatedCodes = <Map<String, String>>[
  <String, String>{
    "name": "Afghanistan",
    "code": "AF",
    "iso3Code": "AFG",
    "dial_code": "+93",
  },
  <String, String>{
    "name": "Aland Islands",
    "code": "AX",
    "iso3Code": "ALA",
    "dial_code": "+358",
  },
  <String, String>{
    "name": "Albania",
    "code": "AL",
    "iso3Code": "ALB",
    "dial_code": "+355",
  },
  <String, String>{
    "name": "Algeria",
    "code": "DZ",
    "iso3Code": "DZA",
    "dial_code": "+213",
  },
  <String, String>{
    "name": "American Samoa",
    "code": "AS",
    "iso3Code": "ASM",
    "dial_code": "+1684",
  },
  <String, String>{
    "name": "Andorra",
    "code": "AD",
    "iso3Code": "AND",
    "dial_code": "+376",
  },
  <String, String>{
    "name": "Angola",
    "code": "AO",
    "iso3Code": "AGO",
    "dial_code": "+244",
  },
  <String, String>{
    "name": "Anguilla",
    "code": "AI",
    "iso3Code": "AIA",
    "dial_code": "+1264",
  },
  <String, String>{
    "name": "Antarctica",
    "code": "AQ",
    "iso3Code": "ATA",
    "dial_code": "+672",
  },
  <String, String>{
    "name": "Antigua and Barbuda",
    "code": "AG",
    "iso3Code": "ATG",
    "dial_code": "+1268",
  },
  <String, String>{
    "name": "Argentina",
    "code": "AR",
    "iso3Code": "ARG",
    "dial_code": "+54",
  },
  <String, String>{
    "name": "Armenia",
    "code": "AM",
    "iso3Code": "ARM",
    "dial_code": "+374",
  },
  <String, String>{
    "name": "Aruba",
    "code": "AW",
    "iso3Code": "ABW",
    "dial_code": "+297",
  },
  <String, String>{
    "name": "Australia",
    "code": "AU",
    "iso3Code": "AUS",
    "dial_code": "+61",
  },
  <String, String>{
    "name": "Austria",
    "code": "AT",
    "iso3Code": "AUT",
    "dial_code": "+43",
  },
  <String, String>{
    "name": "Azerbaijan",
    "code": "AZ",
    "iso3Code": "AZE",
    "dial_code": "+994",
  },
  <String, String>{
    "name": "Bahamas",
    "code": "BS",
    "iso3Code": "BHS",
    "dial_code": "+1242",
  },
  <String, String>{
    "name": "Bahrain",
    "code": "BH",
    "iso3Code": "BHR",
    "dial_code": "+973",
  },
  <String, String>{
    "name": "Bangladesh",
    "code": "BD",
    "iso3Code": "BGD",
    "dial_code": "+880",
  },
  <String, String>{
    "name": "Barbados",
    "code": "BB",
    "iso3Code": "BRB",
    "dial_code": "+1246",
  },
  <String, String>{
    "name": "Belarus",
    "code": "BY",
    "iso3Code": "BLR",
    "dial_code": "+375",
  },
  <String, String>{
    "name": "Belgium",
    "code": "BE",
    "iso3Code": "BEL",
    "dial_code": "+32",
  },
  <String, String>{
    "name": "Belize",
    "code": "BZ",
    "iso3Code": "BLZ",
    "dial_code": "+501",
  },
  <String, String>{
    "name": "Benin",
    "code": "BJ",
    "iso3Code": "BEN",
    "dial_code": "+229",
  },
  <String, String>{
    "name": "Bermuda",
    "code": "BM",
    "iso3Code": "BMU",
    "dial_code": "+1441",
  },
  <String, String>{
    "name": "Bhutan",
    "code": "BT",
    "iso3Code": "BTN",
    "dial_code": "+975",
  },
  <String, String>{
    "name": "Bolivia",
    "code": "BO",
    "iso3Code": "BOL",
    "dial_code": "+591",
  },
  <String, String>{
    "name": "Bosnia and Herzegovina",
    "code": "BA",
    "iso3Code": "BIH",
    "dial_code": "+387",
  },
  <String, String>{
    "name": "Botswana",
    "code": "BW",
    "iso3Code": "BWA",
    "dial_code": "+267",
  },
  <String, String>{
    "name": "Bouvet Island",
    "code": "BV",
    "iso3Code": "BVT",
    "dial_code": "+47",
  },
  <String, String>{
    "name": "Brazil",
    "code": "BR",
    "iso3Code": "BRA",
    "dial_code": "+55",
  },
  <String, String>{
    "name": "British Indian Ocean Territory",
    "code": "IO",
    "iso3Code": "IOT",
    "dial_code": "+246",
  },
  <String, String>{
    "name": "Brunei",
    "code": "BN",
    "iso3Code": "BRN",
    "dial_code": "+673",
  },
  <String, String>{
    "name": "Bulgaria",
    "code": "BG",
    "iso3Code": "BGR",
    "dial_code": "+359",
  },
  <String, String>{
    "name": "Burkina Faso",
    "code": "BF",
    "iso3Code": "BFA",
    "dial_code": "+226",
  },
  <String, String>{
    "name": "Burundi",
    "code": "BI",
    "iso3Code": "BDI",
    "dial_code": "+257",
  },
  <String, String>{
    "name": "Cambodia",
    "code": "KH",
    "iso3Code": "KHM",
    "dial_code": "+855",
  },
  <String, String>{
    "name": "Cameroon",
    "code": "CM",
    "iso3Code": "CMR",
    "dial_code": "+237",
  },
  // {"name": "Canada", "code": "CA", "iso3Code": "CAN", "dial_code": "+1"},
  <String, String>{
    "name": "Cabo Verde",
    "code": "CV",
    "iso3Code": "CPV",
    "dial_code": "+238",
  },
  <String, String>{
    "name": "Cayman Islands",
    "code": "KY",
    "iso3Code": "CYM",
    "dial_code": "+1345",
  },
  <String, String>{
    "name": "Ködörösêse tî Bêafrîka",
    "code": "CF",
    "iso3Code": "CAF",
    "dial_code": "+236",
  },
  <String, String>{
    "name": "Tchad",
    "code": "TD",
    "iso3Code": "TCD",
    "dial_code": "+235",
  },
  <String, String>{
    "name": "Chile",
    "code": "CL",
    "iso3Code": "CHL",
    "dial_code": "+56",
  },
  <String, String>{
    "name": "China",
    "code": "CN",
    "iso3Code": "CHN",
    "dial_code": "+86",
  },
  <String, String>{
    "name": "Christmas Island",
    "code": "CX",
    "iso3Code": "CXR",
    "dial_code": "+61",
  },
  <String, String>{
    "name": "Cocos (Keeling) Islands",
    "code": "CC",
    "iso3Code": "CCK",
    "dial_code": "+61",
  },
  <String, String>{
    "name": "Colombia",
    "code": "CO",
    "iso3Code": "COL",
    "dial_code": "+57",
  },
  <String, String>{
    "name": "Comoros",
    "code": "KM",
    "iso3Code": "COM",
    "dial_code": "+269",
  },
  <String, String>{
    "name": "Republic of the Congo",
    "code": "CG",
    "iso3Code": "COG",
    "dial_code": "+242",
  },
  <String, String>{
    "name": "Democratic Republic of the Congo",
    "code": "CD",
    "iso3Code": "COD",
    "dial_code": "+243",
  },
  <String, String>{
    "name": "Cook Islands",
    "code": "CK",
    "iso3Code": "COK",
    "dial_code": "+682",
  },
  <String, String>{
    "name": "Costa Rica",
    "code": "CR",
    "iso3Code": "CRI",
    "dial_code": "+506",
  },
  <String, String>{
    "name": "Ivory Coast",
    "code": "CI",
    "iso3Code": "CIV",
    "dial_code": "+225",
  },
  <String, String>{
    "name": "Croatia",
    "code": "HR",
    "iso3Code": "HRV",
    "dial_code": "+385",
  },
  <String, String>{
    "name": "Cuba",
    "code": "CU",
    "iso3Code": "CUB",
    "dial_code": "+53",
  },
  <String, String>{
    "name": "Cyprus",
    "code": "CY",
    "iso3Code": "CYP",
    "dial_code": "+357",
  },
  <String, String>{
    "name": "Czech Republic",
    "code": "CZ",
    "iso3Code": "CZE",
    "dial_code": "+420",
  },
  <String, String>{
    "name": "Denmark",
    "code": "DK",
    "iso3Code": "DNK",
    "dial_code": "+45",
  },
  <String, String>{
    "name": "Djibouti",
    "code": "DJ",
    "iso3Code": "DJI",
    "dial_code": "+253",
  },
  <String, String>{
    "name": "Dominica",
    "code": "DM",
    "iso3Code": "DMA",
    "dial_code": "+1767",
  },
  // {
  //   "name": "República Dominicana",
  //   "code": "DO",
  //   "iso3Code": "DOM",
  //   "dial_code": "+1"
  // },
  <String, String>{
    "name": "Ecuador",
    "code": "EC",
    "iso3Code": "ECU",
    "dial_code": "+593",
  },
  <String, String>{
    "name": "Egypt",
    "code": "EG",
    "iso3Code": "EGY",
    "dial_code": "+20",
  },
  <String, String>{
    "name": "El Salvador",
    "code": "SV",
    "iso3Code": "SLV",
    "dial_code": "+503",
  },
  <String, String>{
    "name": "Guinea Ecuatorial",
    "code": "GQ",
    "iso3Code": "GNQ",
    "dial_code": "+240",
  },
  <String, String>{
    "name": "Eritrea",
    "code": "ER",
    "iso3Code": "ERI",
    "dial_code": "+291",
  },
  <String, String>{
    "name": "Eesti",
    "code": "EE",
    "iso3Code": "EST",
    "dial_code": "+372",
  },
  <String, String>{
    "name": "Ethiopia",
    "code": "ET",
    "iso3Code": "ETH",
    "dial_code": "+251",
  },
  <String, String>{
    "name": "Falkland Islands",
    "code": "FK",
    "iso3Code": "FLK",
    "dial_code": "+500",
  },
  <String, String>{
    "name": "Føroyar",
    "code": "FO",
    "iso3Code": "FRO",
    "dial_code": "+298",
  },
  <String, String>{
    "name": "Fiji",
    "code": "FJ",
    "iso3Code": "FJI",
    "dial_code": "+679",
  },
  <String, String>{
    "name": "Finland",
    "code": "FI",
    "iso3Code": "FIN",
    "dial_code": "+358",
  },
  <String, String>{
    "name": "France",
    "code": "FR",
    "iso3Code": "FRA",
    "dial_code": "+33",
  },
  <String, String>{
    "name": "French Guiana",
    "code": "GF",
    "iso3Code": "GUF",
    "dial_code": "+594",
  },
  <String, String>{
    "name": "French Polynesia",
    "code": "PF",
    "iso3Code": "PYF",
    "dial_code": "+689",
  },
  <String, String>{
    "name": "French Southern Territories",
    "code": "TF",
    "iso3Code": "ATF",
    "dial_code": "+262",
  },
  <String, String>{
    "name": "Gabon",
    "code": "GA",
    "iso3Code": "GAB",
    "dial_code": "+241",
  },
  <String, String>{
    "name": "Gambia",
    "code": "GM",
    "iso3Code": "GMB",
    "dial_code": "+220",
  },
  <String, String>{
    "name": "Georgia",
    "code": "GE",
    "iso3Code": "GEO",
    "dial_code": "+995",
  },
  <String, String>{
    "name": "Germany",
    "code": "DE",
    "iso3Code": "DEU",
    "dial_code": "+49",
  },
  <String, String>{
    "name": "Ghana",
    "code": "GH",
    "iso3Code": "GHA",
    "dial_code": "+233",
  },
  <String, String>{
    "name": "Gibraltar",
    "code": "GI",
    "iso3Code": "GIB",
    "dial_code": "+350",
  },
  <String, String>{
    "name": "Greece",
    "code": "GR",
    "iso3Code": "GRC",
    "dial_code": "+30",
  },
  <String, String>{
    "name": "Kalaallit Nunaat",
    "code": "GL",
    "iso3Code": "GRL",
    "dial_code": "+299",
  },
  <String, String>{
    "name": "Grenada",
    "code": "GD",
    "iso3Code": "GRD",
    "dial_code": "+1473",
  },
  <String, String>{
    "name": "Guadeloupe",
    "code": "GP",
    "iso3Code": "GLP",
    "dial_code": "+590",
  },
  <String, String>{
    "name": "Guam",
    "code": "GU",
    "iso3Code": "GUM",
    "dial_code": "+1671",
  },
  <String, String>{
    "name": "Guatemala",
    "code": "GT",
    "iso3Code": "GTM",
    "dial_code": "+502",
  },
  <String, String>{
    "name": "Guernsey",
    "code": "GG",
    "iso3Code": "GGY",
    "dial_code": "+44",
  },
  <String, String>{
    "name": "Guinée",
    "code": "GN",
    "iso3Code": "GIN",
    "dial_code": "+224",
  },
  <String, String>{
    "name": "Guiné-Bissau",
    "code": "GW",
    "iso3Code": "GNB",
    "dial_code": "+245",
  },
  <String, String>{
    "name": "Guyana",
    "code": "GY",
    "iso3Code": "GUY",
    "dial_code": "+592",
  },
  <String, String>{
    "name": "Haïti",
    "code": "HT",
    "iso3Code": "HTI",
    "dial_code": "+509",
  },
  <String, String>{
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "iso3Code": "HMD",
    "dial_code": "+0",
  },
  <String, String>{
    "name": "Vaticano",
    "code": "VA",
    "iso3Code": "VAT",
    "dial_code": "+379",
  },
  <String, String>{
    "name": "Honduras",
    "code": "HN",
    "iso3Code": "HND",
    "dial_code": "+504",
  },
  <String, String>{
    "name": "Hong Kong",
    "code": "HK",
    "iso3Code": "HKG",
    "dial_code": "+852",
  },
  <String, String>{
    "name": "Hungary",
    "code": "HU",
    "iso3Code": "HUN",
    "dial_code": "+36",
  },
  <String, String>{
    "name": "Iceland",
    "code": "IS",
    "iso3Code": "ISL",
    "dial_code": "+354",
  },
  <String, String>{
    "name": "India",
    "code": "IN",
    "iso3Code": "IND",
    "dial_code": "+91",
  },
  <String, String>{
    "name": "Indonesia",
    "code": "ID",
    "iso3Code": "IDN",
    "dial_code": "+62",
  },
  <String, String>{
    "name": "Iran",
    "code": "IR",
    "iso3Code": "IRN",
    "dial_code": "+98",
  },
  <String, String>{
    "name": "Iraq",
    "code": "IQ",
    "iso3Code": "IRQ",
    "dial_code": "+964",
  },
  <String, String>{
    "name": "Ireland",
    "code": "IE",
    "iso3Code": "IRL",
    "dial_code": "+353",
  },
  <String, String>{
    "name": "Isle of Man",
    "code": "IM",
    "iso3Code": "IMN",
    "dial_code": "+44",
  },
  <String, String>{
    "name": "Israel",
    "code": "IL",
    "iso3Code": "ISR",
    "dial_code": "+972",
  },
  <String, String>{
    "name": "Italy",
    "code": "IT",
    "iso3Code": "ITA",
    "dial_code": "+39",
  },
  <String, String>{
    "name": "Jamaica",
    "code": "JM",
    "iso3Code": "JAM",
    "dial_code": "+1876",
  },
  <String, String>{
    "name": "Japan",
    "code": "JP",
    "iso3Code": "JPN",
    "dial_code": "+81",
  },
  <String, String>{
    "name": "Jersey",
    "code": "JE",
    "iso3Code": "JEY",
    "dial_code": "+44",
  },
  <String, String>{
    "name": "Jordan",
    "code": "JO",
    "iso3Code": "JOR",
    "dial_code": "+962",
  },
  <String, String>{
    "name": "Kazakhstan",
    "code": "KZ",
    "iso3Code": "KAZ",
    "dial_code": "+7",
  },
  <String, String>{
    "name": "Kenya",
    "code": "KE",
    "iso3Code": "KEN",
    "dial_code": "+254",
  },
  <String, String>{
    "name": "Kiribati",
    "code": "KI",
    "iso3Code": "KIR",
    "dial_code": "+686",
  },
  <String, String>{
    "name": "North Korea",
    "code": "KP",
    "iso3Code": "PRK",
    "dial_code": "+850",
  },
  <String, String>{
    "name": "South Korea",
    "code": "KR",
    "iso3Code": "KOR",
    "dial_code": "+82",
  },
  <String, String>{
    "name": "Kosovo",
    "code": "XK",
    "iso3Code": "KOS",
    "dial_code": "+383",
  },
  <String, String>{
    "name": "Kuwait",
    "code": "KW",
    "iso3Code": "KWT",
    "dial_code": "+965",
  },
  <String, String>{
    "name": "Kyrgyzstan",
    "code": "KG",
    "iso3Code": "KGZ",
    "dial_code": "+996",
  },
  <String, String>{
    "name": "Laos",
    "code": "LA",
    "iso3Code": "LAO",
    "dial_code": "+856",
  },
  <String, String>{
    "name": "Latvia",
    "code": "LV",
    "iso3Code": "LVA",
    "dial_code": "+371",
  },
  <String, String>{
    "name": "Lebanon",
    "code": "LB",
    "iso3Code": "LBN",
    "dial_code": "+961",
  },
  <String, String>{
    "name": "Lesotho",
    "code": "LS",
    "iso3Code": "LSO",
    "dial_code": "+266",
  },
  <String, String>{
    "name": "Liberia",
    "code": "LR",
    "iso3Code": "LBR",
    "dial_code": "+231",
  },
  <String, String>{
    "name": "Libya",
    "code": "LY",
    "iso3Code": "LBY",
    "dial_code": "+218",
  },
  <String, String>{
    "name": "Liechtenstein",
    "code": "LI",
    "iso3Code": "LIE",
    "dial_code": "+423",
  },
  <String, String>{
    "name": "Lithuania",
    "code": "LT",
    "iso3Code": "LTU",
    "dial_code": "+370",
  },
  <String, String>{
    "name": "Luxembourg",
    "code": "LU",
    "iso3Code": "LUX",
    "dial_code": "+352",
  },
  <String, String>{
    "name": "Macau",
    "code": "MO",
    "iso3Code": "MAC",
    "dial_code": "+853",
  },
  <String, String>{
    "name": "North Macedonia",
    "code": "MK",
    "iso3Code": "MKD",
    "dial_code": "+389",
  },
  <String, String>{
    "name": "Madagasikara",
    "code": "MG",
    "iso3Code": "MDG",
    "dial_code": "+261",
  },
  <String, String>{
    "name": "Malawi",
    "code": "MW",
    "iso3Code": "MWI",
    "dial_code": "+265",
  },
  <String, String>{
    "name": "Malaysia",
    "code": "MY",
    "iso3Code": "MYS",
    "dial_code": "+60",
  },
  <String, String>{
    "name": "Maldives",
    "code": "MV",
    "iso3Code": "MDV",
    "dial_code": "+960",
  },
  <String, String>{
    "name": "Mali",
    "code": "ML",
    "iso3Code": "MLI",
    "dial_code": "+223",
  },
  <String, String>{
    "name": "Malta",
    "code": "MT",
    "iso3Code": "MLT",
    "dial_code": "+356",
  },
  <String, String>{
    "name": "M̧ajeļ",
    "code": "MH",
    "iso3Code": "MHL",
    "dial_code": "+692",
  },
  <String, String>{
    "name": "Martinique",
    "code": "MQ",
    "iso3Code": "MTQ",
    "dial_code": "+596",
  },
  <String, String>{
    "name": "Mauritania",
    "code": "MR",
    "iso3Code": "MRT",
    "dial_code": "+222",
  },
  <String, String>{
    "name": "Maurice",
    "code": "MU",
    "iso3Code": "MUS",
    "dial_code": "+230",
  },
  <String, String>{
    "name": "Mayotte",
    "code": "YT",
    "iso3Code": "MYT",
    "dial_code": "+262",
  },
  <String, String>{
    "name": "Mexico",
    "code": "MX",
    "iso3Code": "MEX",
    "dial_code": "+52",
  },
  <String, String>{
    "name": "Micronesia",
    "code": "FM",
    "iso3Code": "FSM",
    "dial_code": "+691",
  },
  <String, String>{
    "name": "Moldova",
    "code": "MD",
    "iso3Code": "MDA",
    "dial_code": "+373",
  },
  <String, String>{
    "name": "Monaco",
    "code": "MC",
    "iso3Code": "MCO",
    "dial_code": "+377",
  },
  <String, String>{
    "name": "Mongolia",
    "code": "MN",
    "iso3Code": "MNG",
    "dial_code": "+976",
  },
  <String, String>{
    "name": "Montenegro",
    "code": "ME",
    "iso3Code": "MNE",
    "dial_code": "+382",
  },
  <String, String>{
    "name": "Montserrat",
    "code": "MS",
    "iso3Code": "MSR",
    "dial_code": "+1664",
  },
  <String, String>{
    "name": "Morocco",
    "code": "MA",
    "iso3Code": "MAR",
    "dial_code": "+212",
  },
  <String, String>{
    "name": "Moçambique",
    "code": "MZ",
    "iso3Code": "MOZ",
    "dial_code": "+258",
  },
  <String, String>{
    "name": "Myanmar",
    "code": "MM",
    "iso3Code": "MMR",
    "dial_code": "+95",
  },
  <String, String>{
    "name": "Namibia",
    "code": "NA",
    "iso3Code": "NAM",
    "dial_code": "+264",
  },
  <String, String>{
    "name": "Nauru",
    "code": "NR",
    "iso3Code": "NRU",
    "dial_code": "+674",
  },
  <String, String>{
    "name": "Nepal",
    "code": "NP",
    "iso3Code": "NPL",
    "dial_code": "+977",
  },
  <String, String>{
    "name": "Netherlands",
    "code": "NL",
    "iso3Code": "NLD",
    "dial_code": "+31",
  },
  <String, String>{
    "name": "Netherlands Antilles",
    "code": "AN",
    "iso3Code": "AN",
    "dial_code": "+599",
  },
  <String, String>{
    "name": "New Caledonia",
    "code": "NC",
    "iso3Code": "NCL",
    "dial_code": "+687",
  },
  <String, String>{
    "name": "New Zealand",
    "code": "NZ",
    "iso3Code": "NZL",
    "dial_code": "+64",
  },
  <String, String>{
    "name": "Nicaragua",
    "code": "NI",
    "iso3Code": "NIC",
    "dial_code": "+505",
  },
  <String, String>{
    "name": "Niger",
    "code": "NE",
    "iso3Code": "NER",
    "dial_code": "+227",
  },
  <String, String>{
    "name": "Nigeria",
    "code": "NG",
    "iso3Code": "NGA",
    "dial_code": "+234",
  },
  <String, String>{
    "name": "Niuē",
    "code": "NU",
    "iso3Code": "NIU",
    "dial_code": "+683",
  },
  <String, String>{
    "name": "Norfolk Island",
    "code": "NF",
    "iso3Code": "NFK",
    "dial_code": "+672",
  },
  <String, String>{
    "name": "Northern Mariana Islands",
    "code": "MP",
    "iso3Code": "MNP",
    "dial_code": "+1670",
  },
  <String, String>{
    "name": "Norge",
    "code": "NO",
    "iso3Code": "NOR",
    "dial_code": "+47",
  },
  <String, String>{
    "name": "Oman",
    "code": "OM",
    "iso3Code": "OMN",
    "dial_code": "+968",
  },
  <String, String>{
    "name": "Pakistan",
    "code": "PK",
    "iso3Code": "PAK",
    "dial_code": "+92",
  },
  <String, String>{
    "name": "Palau",
    "code": "PW",
    "iso3Code": "PLW",
    "dial_code": "+680",
  },
  <String, String>{
    "name": "Palestine",
    "code": "PS",
    "iso3Code": "PSE",
    "dial_code": "+970",
  },
  <String, String>{
    "name": "Panama",
    "code": "PA",
    "iso3Code": "PAN",
    "dial_code": "+507",
  },
  <String, String>{
    "name": "Papua Niugini",
    "code": "PG",
    "iso3Code": "PNG",
    "dial_code": "+675",
  },
  <String, String>{
    "name": "Paraguay",
    "code": "PY",
    "iso3Code": "PRY",
    "dial_code": "+595",
  },
  <String, String>{
    "name": "Perú",
    "code": "PE",
    "iso3Code": "PER",
    "dial_code": "+51",
  },
  <String, String>{
    "name": "Pilipinas",
    "code": "PH",
    "iso3Code": "PHL",
    "dial_code": "+63",
  },
  <String, String>{
    "name": "Pitcairn Islands",
    "code": "PN",
    "iso3Code": "PCN",
    "dial_code": "+64",
  },
  <String, String>{
    "name": "Polska",
    "code": "PL",
    "iso3Code": "POL",
    "dial_code": "+48",
  },
  <String, String>{
    "name": "Portugal",
    "code": "PT",
    "iso3Code": "PRT",
    "dial_code": "+351",
  },
  <String, String>{
    "name": "Puerto Rico",
    "code": "PR",
    "iso3Code": "PRI",
    "dial_code": "+1939",
  },
  <String, String>{
    "name": "Puerto Rico",
    "code": "PR",
    "iso3Code": "PRI",
    "dial_code": "+1787",
  },
  <String, String>{
    "name": "Qatar",
    "code": "QA",
    "iso3Code": "QAT",
    "dial_code": "+974",
  },
  <String, String>{
    "name": "Romania",
    "code": "RO",
    "iso3Code": "ROU",
    "dial_code": "+40",
  },
  <String, String>{
    "name": "Russia",
    "code": "RU",
    "iso3Code": "RUS",
    "dial_code": "+7",
  },
  <String, String>{
    "name": "Rwanda",
    "code": "RW",
    "iso3Code": "RWA",
    "dial_code": "+250",
  },
  <String, String>{
    "name": "La Réunion",
    "code": "RE",
    "iso3Code": "REU",
    "dial_code": "+262",
  },
  <String, String>{
    "name": "Saint-Barthélemy",
    "code": "BL",
    "iso3Code": "BLM",
    "dial_code": "+590",
  },
  <String, String>{
    "name": "Saint Helena",
    "code": "SH",
    "iso3Code": "SHN",
    "dial_code": "+290",
  },
  <String, String>{
    "name": "Saint Kitts and Nevis",
    "code": "KN",
    "iso3Code": "KNA",
    "dial_code": "+1869",
  },
  <String, String>{
    "name": "Saint Lucia",
    "code": "LC",
    "iso3Code": "LCA",
    "dial_code": "+1758",
  },
  <String, String>{
    "name": "Saint-Martin",
    "code": "MF",
    "iso3Code": "MAF",
    "dial_code": "+590",
  },
  <String, String>{
    "name": "Saint-Pierre-et-Miquelon",
    "code": "PM",
    "iso3Code": "SPM",
    "dial_code": "+508",
  },
  <String, String>{
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "iso3Code": "VCT",
    "dial_code": "+1784",
  },
  <String, String>{
    "name": "Samoa",
    "code": "WS",
    "iso3Code": "WSM",
    "dial_code": "+685",
  },
  <String, String>{
    "name": "San Marino",
    "code": "SM",
    "iso3Code": "SMR",
    "dial_code": "+378",
  },
  <String, String>{
    "name": "São Tomé e Príncipe",
    "code": "ST",
    "iso3Code": "STP",
    "dial_code": "+239",
  },
  <String, String>{
    "name": "Kingdom of Saudi Arabia",
    "code": "SA",
    "iso3Code": "SAU",
    "dial_code": "+966",
  },
  <String, String>{
    "name": "Sénégal",
    "code": "SN",
    "iso3Code": "SEN",
    "dial_code": "+221",
  },
  <String, String>{
    "name": "Србија",
    "code": "RS",
    "iso3Code": "SRB",
    "dial_code": "+381",
  },
  <String, String>{
    "name": "Seychelles",
    "code": "SC",
    "iso3Code": "SYC",
    "dial_code": "+248",
  },
  <String, String>{
    "name": "Sierra Leone",
    "code": "SL",
    "iso3Code": "SLE",
    "dial_code": "+232",
  },
  <String, String>{
    "name": "Singapore",
    "code": "SG",
    "iso3Code": "SGP",
    "dial_code": "+65",
  },
  <String, String>{
    "name": "Slovensko",
    "code": "SK",
    "iso3Code": "SVK",
    "dial_code": "+421",
  },
  <String, String>{
    "name": "Slovenija",
    "code": "SI",
    "iso3Code": "SVN",
    "dial_code": "+386",
  },
  <String, String>{
    "name": "Solomon Islands",
    "code": "SB",
    "iso3Code": "SLB",
    "dial_code": "+677",
  },
  <String, String>{
    "name": "Soomaaliya",
    "code": "SO",
    "iso3Code": "SOM",
    "dial_code": "+252",
  },
  <String, String>{
    "name": "South Africa",
    "code": "ZA",
    "iso3Code": "ZAF",
    "dial_code": "+27",
  },
  <String, String>{
    "name": "South Sudan",
    "code": "SS",
    "iso3Code": "SSD",
    "dial_code": "+211",
  },
  <String, String>{
    "name": "South Georgia",
    "code": "GS",
    "iso3Code": "SGS",
    "dial_code": "+500",
  },
  <String, String>{
    "name": "España",
    "code": "ES",
    "iso3Code": "ESP",
    "dial_code": "+34",
  },
  <String, String>{
    "name": "Sri Lanka",
    "code": "LK",
    "iso3Code": "LKA",
    "dial_code": "+94",
  },
  <String, String>{
    "name": "Sudan",
    "code": "SD",
    "iso3Code": "SDN",
    "dial_code": "+249",
  },
  <String, String>{
    "name": "Suriname",
    "code": "SR",
    "iso3Code": "SUR",
    "dial_code": "+597",
  },
  <String, String>{
    "name": "Svalbard og Jan Mayen",
    "code": "SJ",
    "iso3Code": "SJM",
    "dial_code": "+47",
  },
  <String, String>{
    "name": "Swaziland",
    "code": "SZ",
    "iso3Code": "SWZ",
    "dial_code": "+268",
  },
  <String, String>{
    "name": "Sweden",
    "code": "SE",
    "iso3Code": "SWE",
    "dial_code": "+46",
  },
  <String, String>{
    "name": "Switzerland",
    "code": "CH",
    "iso3Code": "CHE",
    "dial_code": "+41",
  },
  <String, String>{
    "name": "Syria",
    "code": "SY",
    "iso3Code": "SYR",
    "dial_code": "+963",
  },
  <String, String>{
    "name": "Taiwan",
    "code": "TW",
    "iso3Code": "TWN",
    "dial_code": "+886",
  },
  <String, String>{
    "name": "Tajikistan",
    "code": "TJ",
    "iso3Code": "TJK",
    "dial_code": "+992",
  },
  <String, String>{
    "name": "Tanzania",
    "code": "TZ",
    "iso3Code": "TZA",
    "dial_code": "+255",
  },
  <String, String>{
    "name": "Thailand",
    "code": "TH",
    "iso3Code": "THA",
    "dial_code": "+66",
  },
  <String, String>{
    "name": "Timor-Leste",
    "code": "TL",
    "iso3Code": "TLS",
    "dial_code": "+670",
  },
  <String, String>{
    "name": "Togo",
    "code": "TG",
    "iso3Code": "TGO",
    "dial_code": "+228",
  },
  <String, String>{
    "name": "Tokelau",
    "code": "TK",
    "iso3Code": "TKL",
    "dial_code": "+690",
  },
  <String, String>{
    "name": "Tonga",
    "code": "TO",
    "iso3Code": "TON",
    "dial_code": "+676",
  },
  <String, String>{
    "name": "Trinidad and Tobago",
    "code": "TT",
    "iso3Code": "TTO",
    "dial_code": "+1868",
  },
  <String, String>{
    "name": "Tunisia",
    "code": "TN",
    "iso3Code": "TUN",
    "dial_code": "+216",
  },
  <String, String>{
    "name": "Turkey",
    "code": "TR",
    "iso3Code": "TUR",
    "dial_code": "+90",
  },
  <String, String>{
    "name": "Turkmenistan",
    "code": "TM",
    "iso3Code": "TKM",
    "dial_code": "+993",
  },
  <String, String>{
    "name": "Turks and Caicos Islands",
    "code": "TC",
    "iso3Code": "TCA",
    "dial_code": "+1649",
  },
  <String, String>{
    "name": "Tuvalu",
    "code": "TV",
    "iso3Code": "TUV",
    "dial_code": "+688",
  },
  <String, String>{
    "name": "Uganda",
    "code": "UG",
    "iso3Code": "UGA",
    "dial_code": "+256",
  },
  <String, String>{
    "name": "Ukraine",
    "code": "UA",
    "iso3Code": "UKR",
    "dial_code": "+380",
  },
  <String, String>{
    "name": "United Arab Emirates",
    "code": "AE",
    "iso3Code": "ARE",
    "dial_code": "+971",
  },
  <String, String>{
    "name": "United Kingdom",
    "code": "GB",
    "iso3Code": "GBR",
    "dial_code": "+44",
  },
  <String, String>{
    "name": "United States",
    "code": "US",
    "iso3Code": "USA",
    "dial_code": "+1",
  },
  <String, String>{
    "name": "Uruguay",
    "code": "UY",
    "iso3Code": "URY",
    "dial_code": "+598",
  },
  <String, String>{
    "name": "O‘zbekiston",
    "code": "UZ",
    "iso3Code": "UZB",
    "dial_code": "+998",
  },
  <String, String>{
    "name": "Vanuatu",
    "code": "VU",
    "iso3Code": "VUT",
    "dial_code": "+678",
  },
  <String, String>{
    "name": "Venezuela",
    "code": "VE",
    "iso3Code": "VEN",
    "dial_code": "+58",
  },
  <String, String>{
    "name": "Việt Nam",
    "code": "VN",
    "iso3Code": "VNM",
    "dial_code": "+84",
  },
  <String, String>{
    "name": "British Virgin Islands",
    "code": "VG",
    "iso3Code": "VGB",
    "dial_code": "+1284",
  },
  <String, String>{
    "name": "United States Virgin Islands",
    "code": "VI",
    "iso3Code": "VIR",
    "dial_code": "+1340",
  },
  <String, String>{
    "name": "Wallis et Futuna",
    "code": "WF",
    "iso3Code": "WLF",
    "dial_code": "+681",
  },
  <String, String>{
    "name": "Yemen",
    "code": "YE",
    "iso3Code": "YEM",
    "dial_code": "+967",
  },
  <String, String>{
    "name": "Zambia",
    "code": "ZM",
    "iso3Code": "ZMB",
    "dial_code": "+260",
  },
  <String, String>{
    "name": "Zimbabwe",
    "code": "ZW",
    "iso3Code": "ZWE",
    "dial_code": "+263",
  },
];
