List<Map<String, dynamic>> temporaryViewModel = [
  {
    "user_id": 640,
    "name": "Mohsin Ali sir",
    "email": "mohsinali@irvinei.com",
    "phone_number": "+923343683084",
    "role": null,
    "is_accepted": null,
    "invite_id": null,
    "user_exist": true,
    "source": "user",
    "profile_image": "images/640/scaled_1000071573.png",
  },
  {
    "user_id": 9,
    "name": "Haleema Afshan Khanz",
    "email": "haleemaafshan@irvinei.com",
    "phone_number": "+923363052172",
    "role": "Admin",
    "is_accepted": null,
    "invite_id": null,
    "user_exist": true,
    "source": "user",
    "profile_image": "images/9/compressed_scaled_1000044925.jpg",
  },
  {
    "user_id": 639,
    "name": "test",
    "email": "testwfh005@gmail.com",
    "phone_number": "+923312141298",
    "role": "Admin",
    "is_accepted": null,
    "invite_id": null,
    "user_exist": true,
    "source": "user",
    "profile_image":
        "images/639/compressed_scaled_Screenshot_20240826-170806_Irvinei Mobile App.jpg",
  },
  {
    "user_id": 4,
    "name": "Hamza Siddiqui",
    "email": "hamzasiddiqui@irvinei.com",
    "phone_number": "+923442066268",
    "role": "Viewer",
    "is_accepted": null,
    "invite_id": null,
    "user_exist": true,
    "source": "user",
    "profile_image": null,
  }
];
